// GENERADO por scripts/gen-shirt-names.mjs desde lib/data/squads_wc2026.csv — NO editar a mano.
// ISO2 (flagcdn) → lista de [nombre_completo, nombre_camiseta] de la convocatoria WC2026.
// El resolver con match por tokens vive en lib/shirt-names.ts.
export const SHIRT_NAMES: Record<string, [string, string][]> = {
  "ar": [
    ["MUSSO Juan", "MUSSO"],
    ["SENESI Marcos", "SENESI"],
    ["TAGLIAFICO Nicolas", "TAGLIAFICO"],
    ["MONTIEL Gonzalo", "MONTIEL"],
    ["PAREDES Leandro", "PAREDES"],
    ["MARTINEZ Lisandro", "MARTÍNEZ"],
    ["DE PAUL Rodrigo", "DE PAUL"],
    ["BARCO Valentin", "BARCO"],
    ["ALVAREZ Julian", "J. ALVAREZ"],
    ["MESSI Lionel", "MESSI"],
    ["LO CELSO Giovani", "LO CELSO"],
    ["RULLI Geronimo", "RULLI"],
    ["ROMERO Cristian", "ROMERO"],
    ["PALACIOS Exequiel", "PALACIOS"],
    ["GONZALEZ Nico", "N. GONZALEZ"],
    ["ALMADA Thiago", "ALMADA"],
    ["SIMEONE Giuliano", "SIMEONE"],
    ["PAZ Nico", "NICO PAZ"],
    ["OTAMENDI Nicolas", "OTAMENDI"],
    ["MAC ALLISTER Alexis", "MAC ALLISTER"],
    ["LOPEZ Jose Manuel", "LOPEZ"],
    ["MARTINEZ Lautaro", "L. MARTINEZ"],
    ["MARTINEZ Emiliano", "E. MARTINEZ"],
    ["FERNANDEZ Enzo", "E. FERNANDEZ"],
    ["MEDINA Facundo", "MEDINA"],
    ["MOLINA Nahuel", "MOLINA"],
  ],
  "at": [
    ["SCHLAGER Alexander", "SCHLAGER"],
    ["AFFENGRUBER David", "AFFENGRUBER"],
    ["DANSO Kevin", "DANSO"],
    ["SCHLAGER Xaver", "XAVER"],
    ["POSCH Stefan", "POSCH"],
    ["SEIWALD Nicolas", "SEIWALD"],
    ["ARNAUTOVIC Marko", "ARNAUTOVIC"],
    ["ALABA David", "ALABA"],
    ["SABITZER Marcel", "SABITZER"],
    ["GRILLITSCH Florian", "GRILLITSCH"],
    ["GREGORITSCH Michael", "GREGORITSCH"],
    ["WIEGELE Florian", "WIEGELE"],
    ["PENTZ Patrick", "PENTZ"],
    ["KALAJDZIC Sasa", "KALAJDZIC"],
    ["LIENHART Philipp", "LIENHART"],
    ["MWENE Phillip", "MWENE"],
    ["CHUKWUEMEKA Carney", "CHUKWUEMEKA"],
    ["SCHMID Romano", "SCHMID"],
    ["LJUBICIC Dejan", "LJUBICIC"],
    ["LAIMER Konrad", "LAIMER"],
    ["WIMMER Patrick", "WIMMER"],
    ["PRASS Alexander", "PRASS"],
    ["FRIEDL Marco", "FRIEDL"],
    ["WANNER Paul", "WANNER"],
    ["SVOBODA Michael", "SVOBODA"],
    ["SCHOEPF Alessandro", "SCHÖPF"],
  ],
  "au": [
    ["RYAN Mathew", "RYAN"],
    ["DEGENEK Milos", "DEGENEK"],
    ["CIRCATI Alessandro", "CIRCATI"],
    ["ITALIANO Jacob", "ITALIANO"],
    ["BOS Jordan", "BOS"],
    ["GERIA Jason", "GERIA"],
    ["LECKIE Mathew", "LECKIE"],
    ["METCALFE Connor", "METCALFE"],
    ["TOURE Mohamed", "TOURE"],
    ["HRUSTIC Ajdin", "HRUSTIC"],
    ["MABIL Awer", "MABIL"],
    ["IZZO Paul", "IZZO"],
    ["ONEILL Aiden", "O'NEILL"],
    ["DEVLIN Cameron", "DEVLIN"],
    ["TREWIN Kai", "TREWIN"],
    ["BEHICH Aziz", "BEHICH"],
    ["IRANKUNDA Nestory", "IRANKUNDA"],
    ["BEACH Patrick", "BEACH"],
    ["SOUTTAR Harry", "SOUTTAR"],
    ["VOLPATO Cristian", "VOLPATO"],
    ["BURGESS Cameron", "BURGESS"],
    ["IRVINE Jackson", "IRVINE"],
    ["VELUPILLAY Nishan", "VELUPILLAY"],
    ["OKON-ENGSTLER Paul", "OKON-ENGSTLER"],
    ["HERRINGTON Lucas", "HERRINGTON"],
    ["YENGI Tete", "YENGI"],
  ],
  "ba": [
    ["VASILJ Nikola", "VASILJ"],
    ["MUJAKIC Nihad", "MUJAKIĆ"],
    ["HADZIKADUNIC Dennis", "HADŽIKADUNIĆ"],
    ["MUHAREMOVIC Tarik", "MUHAREMOVIĆ"],
    ["KOLASINAC Sead", "KOLAŠINAC"],
    ["TAHIROVIC Benjamin", "TAHIROVIĆ"],
    ["DEDIC Amar", "DEDIĆ"],
    ["GIGOVIC Armin", "GIGOVIĆ"],
    ["BAZDAR Samed", "BAŽDAR"],
    ["DEMIROVIC Ermedin", "DEMIROVIĆ"],
    ["DZEKO Edin", "DŽEKO"],
    ["JURKAS Mladen", "JURKAS"],
    ["BASIC Ivan", "BAŠIĆ"],
    ["SUNJIC Ivan", "ŠUNJIĆ"],
    ["MEMIC Amar", "MEMIĆ"],
    ["HADZIAHMETOVIC Amir", "HADŽIAHMETOVIĆ"],
    ["BURNIC Dzenis", "BURNIĆ"],
    ["KATIC Nikola", "KATIĆ"],
    ["ALAJBEGOVIC Kerim", "ALAJBEGOVIĆ"],
    ["BAJRAKTAREVIC Esmir", "BAJRAKTAREVIĆ"],
    ["RADELJIC Stjepan", "RADELJIĆ"],
    ["ZLOMISLIC Martin", "ZLOMISLIĆ"],
    ["TABAKOVIC Haris", "TABAKOVIĆ"],
    ["MALIC Arjan", "MALIĆ"],
    ["LUKIC Jovo", "LUKIĆ"],
    ["MAHMIC Ermin", "MAHMIĆ"],
  ],
  "be": [
    ["COURTOIS Thibaut", "COURTOIS"],
    ["DEBAST Zeno", "DEBAST"],
    ["THEATE Arthur", "THEATE"],
    ["MECHELE Brandon", "MECHELE"],
    ["DE CUYPER Maxim", "DE CUYPER"],
    ["WITSEL Axel", "WITSEL"],
    ["DE BRUYNE Kevin", "DE BRUYNE"],
    ["TIELEMANS Youri", "TIELEMANS"],
    ["LUKAKU Romelu", "LUKAKU"],
    ["TROSSARD Leandro", "TROSSARD"],
    ["DOKU Jeremy", "DOKU"],
    ["LAMMENS Senne", "LAMMENS"],
    ["PENDERS Mike", "PENDERS"],
    ["LUKEBAKIO Dodi", "LUKEBAKIO"],
    ["MEUNIER Thomas", "MEUNIER"],
    ["DE WINTER Koni", "DE WINTER"],
    ["DE KETELAERE Charles", "DE KETELAERE"],
    ["SEYS Joaquin", "SEYS"],
    ["MOREIRA Diego", "MOREIRA JR"],
    ["VANAKEN Hans", "VANAKEN"],
    ["CASTAGNE Timothy", "CASTAGNE"],
    ["SAELEMAEKERS Alexis", "SAELEMAEKERS"],
    ["RASKIN Nicolas", "RASKIN"],
    ["ONANA Amadou", "ONANA"],
    ["NGOY Nathan", "NGOY"],
    ["FERNANDEZ-PARDO Matias", "FERNANDEZ-PARDO"],
  ],
  "br": [
    ["ALISSON", "A. BECKER"],
    ["EDERSON SILVA", "ÉDERSON S."],
    ["GABRIEL MAGALHAES", "GABRIEL"],
    ["MARQUINHOS", "MARQUINHOS"],
    ["CASEMIRO", "CASEMIRO"],
    ["ALEX SANDRO", "ALEX SANDRO"],
    ["VINICIUS JUNIOR", "VINI JR."],
    ["BRUNO GUIMARAES", "BRUNO G."],
    ["MATHEUS CUNHA", "CUNHA"],
    ["NEYMAR JR", "NEYMAR JR"],
    ["RAPHINHA", "RAPHINHA"],
    ["WEVERTON", "WEVERTON"],
    ["DANILO", "DANILO"],
    ["BREMER", "BREMER"],
    ["LEO PEREIRA", "LÉO PEREIRA"],
    ["DOUGLAS SANTOS", "DOUGLAS S."],
    ["FABINHO", "FABINHO"],
    ["DANILO SANTOS", "DANILO S."],
    ["ENDRICK", "ENDRICK"],
    ["LUCAS PAQUETA", "L. PAQUETÁ"],
    ["LUIZ HENRIQUE", "L. HENRIQUE"],
    ["GABRIEL MARTINELLI", "MARTINELLI"],
    ["EDERSON", "EDERSON"],
    ["ROGER IBANEZ", "IBAÑEZ"],
    ["IGOR THIAGO", "THIAGO"],
    ["RAYAN", "RAYAN"],
  ],
  "ca": [
    ["ST. CLAIR Dayne", "ST. CLAIR"],
    ["JOHNSTON Alistair", "JOHNSTON"],
    ["JONES Al«e", "JONES"],
    ["DE FOUGEROLLES Luc", "DE FOUGEROLLES"],
    ["WATERMAN Joel", "WATERMAN"],
    ["CHOINIERE Mathieu", "CHOINIÈRE"],
    ["EUSTAQUIO Stephen", "EUSTÁQUIO"],
    ["KONE Ismael", "KONÉ"],
    ["LARIN Cyle", "LARIN"],
    ["DAVID Jonathan", "J. DAVID"],
    ["MILLAR Liam", "MILLAR"],
    ["OLUWASEYI Tani", "OLUWASEYI"],
    ["CORNELIUS Derek", "CORNELIUS"],
    ["SHAFFELBURG Jacob", "SHAFFELBURG"],
    ["BOMBITO Moise", "BOMBITO"],
    ["CREPEAU Maxime", "CRÉPEAU"],
    ["BUCHANAN Tajon", "BUCHANAN"],
    ["GOODMAN Owen", "GOODMAN"],
    ["DAVIES Alphonso", "DAVIES"],
    ["AHMED Ali", "AHMED"],
    ["OSORIO Jonathan", "OSORIO"],
    ["LARYEA Richie", "LARYEA"],
    ["SIGUR Niko", "SIGUR"],
    ["DAVID Promise", "PROMISE"],
    ["SALIBA Nathan", "SALIBA"],
    ["NELSON Jayden", "NELSON"],
  ],
  "cd": [
    ["MPASI Lionel", "MPASI"],
    ["WAN-BISSAKA Aaron", "WAN BISSAKA"],
    ["KAPUADI Steve", "KAPUADI"],
    ["TUANZEBE Axel", "TUANZEBE"],
    ["BATUBINSIKA Dylan", "BATUBINSIKA"],
    ["MUKAU Ngalayel", "MUKAU"],
    ["MBUKU Nathanael", "MBUKU"],
    ["MOUTOUSSAMY Samuel", "MOUTOUSSAMY"],
    ["CIPENGA Brian", "CIPENGA"],
    ["BONGONDA Theo", "BONGONDA"],
    ["KAKUTA Gael", "KAKUTA"],
    ["KAYEMBE Joris", "J. KAYEMBE"],
    ["ELIA Meschack", "MESCHACK"],
    ["SADIKI Noah", "SADIKI"],
    ["TSHIBOLA Aaron", "TSHIBOLA"],
    ["FAYULU Timothy", "FAYULU"],
    ["BAKAMBU Cedric", "BAKAMBU"],
    ["PICKEL Charles", "PICKEL"],
    ["MAYELE Fiston", "MAYELE"],
    ["WISSA Yoane", "WISSA"],
    ["EPOLO Matthieu", "EPOLO"],
    ["MBEMBA Chancel", "MBEMBA"],
    ["BANZA Simon", "BANZA"],
    ["KALULU Gedeon", "KALULU"],
    ["KAYEMBE Edo", "E. KAYEMBE"],
    ["MASUAKU Arthur", "MASUAKU"],
  ],
  "ch": [
    ["KOBEL Gregor", "KOBEL"],
    ["MUHEIM Miro", "MUHEIM"],
    ["WIDMER Silvan", "WIDMER"],
    ["ELVEDI Nico", "ELVEDI"],
    ["AKANJI Manuel", "AKANJI"],
    ["ZAKARIA Denis", "ZAKARIA"],
    ["EMBOLO Breel", "EMBOLO"],
    ["FREULER Remo", "FREULER"],
    ["MANZAMBI Johan", "MANZAMBI"],
    ["XHAKA Granit", "XHAKA"],
    ["NDOYE Dan", "NDOYE"],
    ["MVOGO Yvon", "MVOGO"],
    ["RODRIGUEZ Ricardo", "RODRIGUEZ"],
    ["JASHARI Ardon", "JASHARI"],
    ["SOW Djibril", "SOW"],
    ["FASSNACHT Christian", "FASSNACHT"],
    ["VARGAS Ruben", "VARGAS"],
    ["COEMERT Eray", "CÖMERT"],
    ["OKAFOR Noah", "OKAFOR"],
    ["AEBISCHER Michel", "AEBISCHER"],
    ["KELLER Marvin", "KELLER"],
    ["RIEDER Fabian", "RIEDER"],
    ["AMDOUNI Zeki", "AMDOUNI"],
    ["AMENDA Aurele", "AMENDA"],
    ["JAQUEZ Luca", "JAQUEZ"],
    ["ITTEN Cedric", "ITTEN"],
  ],
  "ci": [
    ["FOFANA Yahia", "Y. FOFANA"],
    ["DIOMANDE Ousmane", "O. DIOMANDE"],
    ["KONAN Ghislain", "G. KONAN"],
    ["SERI Jean Michael", "SERI"],
    ["SINGO Wilfried", "SINGO"],
    ["FOFANA Seko", "FOFANA"],
    ["KOSSOUNOU Odilon", "KOSSOUNOU"],
    ["KESSIE Franck", "KESSIE"],
    ["BONNY Ange-Yoan", "BONNY"],
    ["ADINGRA Simon", "ADINGRA"],
    ["DIOMANDE Yan", "YAN DIOMANDE"],
    ["WAHI Elye", "WAHI"],
    ["OPERI Christopher", "OPERI"],
    ["DIAKITE Oumar", "DIAKITE"],
    ["DIALLO Amad", "AMAD"],
    ["KONE Mohamed", "KONE"],
    ["DOUE Guela", "G. DOUE"],
    ["SANGARE Ibrahim", "SANGARE"],
    ["PEPE Nicolas", "PEPE"],
    ["AGBADOU Emmanuel", "AGBADOU"],
    ["NDICKA Evan", "NDICKA"],
    ["GUESSAND Evann", "GUESSAND"],
    ["LAFONT Alban", "LAFONT"],
    ["TOURE Bazoumana", "TOURE"],
    ["GUIAGON Parfait", "GUIAGON"],
    ["OULAI Christ Inao", "INAO"],
  ],
  "co": [
    ["OSPINA David", "OSPINA"],
    ["MUNOZ Daniel", "D. MUÑOZ"],
    ["LUCUMI Jhon", "J. LUCUMI"],
    ["ARIAS Santiago", "ARIAS"],
    ["CASTANO Kevin", "K. CASTAÑO"],
    ["RIOS Richard", "RICHARD RIOS"],
    ["DIAZ Luis", "LUIS DIAZ"],
    ["CARRASCAL Jorge", "CARRASCAL"],
    ["CORDOBA Jhon", "CORDOBA"],
    ["RODRIGUEZ James", "JAMES"],
    ["ARIAS Jhon", "J. ARIAS"],
    ["VARGAS Camilo", "C. VARGAS"],
    ["MINA Yerry", "Y. MINA"],
    ["PUERTA Gustavo", "PUERTA"],
    ["PORTILLA Juan", "PORTILLA"],
    ["LERMA Jefferson", "J. LERMA"],
    ["MOJICA Johan", "J. MOJICA"],
    ["DITTA Willer", "W. DITTA"],
    ["HERNANDEZ Cucho", "C. HERNANDEZ"],
    ["QUINTERO Juan", "QUINTERO"],
    ["CAMPAZ Jaminton", "CAMPAZ"],
    ["MACHADO Deiver", "MACHADO"],
    ["SANCHEZ Davinson", "SANCHEZ"],
    ["MONTERO Alvaro", "MONTERO"],
    ["SUAREZ Luis", "SUAREZ"],
    ["GOMEZ Andres", "A. GOMEZ"],
  ],
  "cv": [
    ["VOZINHA", "VOZINHA"],
    ["STOPIRA", "STOPIRA"],
    ["DINEY BORGES", "BORGES"],
    ["PICO LOPES", "LOPES"],
    ["LOGAN COSTA", "COSTA"],
    ["KEVIN PINA", "KEVIN L."],
    ["JOVANE CABRAL", "JOVANE"],
    ["JOAO PAULO", "JOÃO PAULO"],
    ["GILSON BENCHIMOL", "BENCHIMOL"],
    ["JAMIRO MONTEIRO", "MONTEIRO"],
    ["GARRY RODRIGUES", "RODRIGUES"],
    ["MARCIO ROSA", "MARCIO"],
    ["SIDNY LOPES CABRAL", "LOPES CABRAL"],
    ["DEROY DUARTE", "D. DUARTE"],
    ["LAROS DUARTE", "L. DUARTE"],
    ["YANNICK SEMEDO", "Y. SEMEDO"],
    ["WILLY SEMEDO", "SEMEDO"],
    ["TELMO ARCANJO", "ARCANJO"],
    ["DAILON LIVRAMENTO", "LIVRAMENTO"],
    ["RYAN MENDES", "RYAN"],
    ["NUNO DA COSTA", "DA COSTA"],
    ["STEVEN MOREIRA", "MOREIRA"],
    ["CJ DOS SANTOS", "DOS SANTOS"],
    ["WAGNER PINA", "WAGNER P."],
    ["KELVIN PIRES", "KELVIN"],
    ["HELIO VARELA", "HÉLIO"],
  ],
  "cw": [
    ["ROOM Eloy", "ROOM"],
    ["SAMBO Shurandy", "SAMBO"],
    ["GAARI Jurien", "GAARI"],
    ["VAN EIJMA Roshon", "VAN EIJMA"],
    ["FLORANUS Sherel", "FLORANUS"],
    ["ROEMERATOE Godfried", "ROEMERATOE"],
    ["BACUNA Juninho", "J. BACUNA"],
    ["COMENENCIA Livano", "COMENENCIA"],
    ["LOCADIA Juergen", "LOCADIA"],
    ["BACUNA Leandro", "L. BACUNA"],
    ["ANTONISSE Jeremy", "ANTONISSE"],
    ["HANSEN Sontje", "HANSEN"],
    ["NOSLIN Tyrese", "NOSLIN"],
    ["GORRE Kenji", "GORRÉ"],
    ["MARTHA Arjany", "MARTHA"],
    ["MARGARITHA Jearl", "MARGARITHA"],
    ["KUWAS Brandley", "KUWAS"],
    ["OBISPO Armando", "OBISPO"],
    ["KASTANEER Gervane", "KASTANEER"],
    ["BRENET Joshua", "BRENET"],
    ["CHONG Tahith", "CHONG"],
    ["FELIDA Kevin", "FELIDA"],
    ["BAZOER Riechedly", "BAZOER"],
    ["FONVILLE Deveron", "FONVILLE"],
    ["BODAK Tyrick", "BODAK"],
    ["DOORNBUSCH Trevor", "DOORNBUSCH"],
  ],
  "cz": [
    ["KOVAR Matej", "KOVÁŘ"],
    ["ZIMA David", "ZIMA"],
    ["HOLES Tomas", "HOLEŠ"],
    ["HRANAC Robin", "HRANÁČ"],
    ["COUFAL Vladimir", "COUFAL"],
    ["CHALOUPEK Stepan", "CHALOUPEK"],
    ["KREJCI Ladislav", "KREJČÍ"],
    ["DARIDA Vladimir", "DARIDA"],
    ["HLOZEK Adam", "HLOŽEK"],
    ["SCHICK Patrik", "SCHICK"],
    ["KUCHTA Jan", "KUCHTA"],
    ["CERV Lukas", "ČERV"],
    ["CHYTIL Mojmir", "CHYTIL"],
    ["JURASEK David", "JURÁSEK"],
    ["SULC Pavel", "ŠULC"],
    ["STANEK Jindrich", "STANĚK"],
    ["PROVOD Lukas", "PROVOD"],
    ["SADILEK Michal", "SADÍLEK"],
    ["CHORY Tomas", "CHORÝ"],
    ["ZELENY Jaroslav", "ZELENÝ"],
    ["DOUDERA David", "DOUDĚRA"],
    ["SOUCEK Tomas", "SOUČEK"],
    ["HORNICEK Lukas", "HORNÍČEK"],
    ["SOJKA Alexandr", "SOJKA"],
    ["SOCHUREK Hugo", "SOCHŮREK"],
    ["VISINSKY Denis", "VIŠINSKÝ"],
  ],
  "de": [
    ["NEUER Manuel", "NEUER"],
    ["RUEDIGER Antonio", "RÜDIGER"],
    ["ANTON Waldemar", "ANTON"],
    ["TAH Jonathan", "TAH"],
    ["PAVLOVIC Aleksandar", "PAVLOVIĆ"],
    ["KIMMICH Joshua", "KIMMICH"],
    ["HAVERTZ Kai", "HAVERTZ"],
    ["GORETZKA Leon", "GORETZKA"],
    ["LEWELING Jamie", "LEWELING"],
    ["MUSIALA Jamal", "MUSIALA"],
    ["WOLTEMADE Nick", "WOLTEMADE"],
    ["BAUMANN Oliver", "BAUMANN"],
    ["GROSS Pascal", "GROß"],
    ["BEIER Maximilian", "BEIER"],
    ["SCHLOTTERBECK Nico", "SCHLOTTERBECK"],
    ["STILLER Angelo", "STILLER"],
    ["WIRTZ Florian", "WIRTZ"],
    ["BROWN Nathaniel", "BROWN"],
    ["SANE Leroy", "SANÉ"],
    ["AMIRI Nadiem", "AMIRI"],
    ["NUEBEL Alexander", "NÜBEL"],
    ["RAUM David", "RAUM"],
    ["NMECHA Felix", "NMECHA"],
    ["THIAW Malick", "THIAW"],
    ["OUEDRAOGO Assan", "OUÉDRAOGO"],
    ["UNDAV Deniz", "UNDAV"],
  ],
  "dz": [
    ["MASTIL Melvin", "MASTIL"],
    ["MANDI Aissa", "MANDI"],
    ["ABADA Achref", "ABADA"],
    ["TOUGAI Mohamed Amine", "TOUGAI"],
    ["BELAID Zineddine", "BELAID"],
    ["ZERROUKI Ramiz", "ZERROUKI"],
    ["MAHREZ Riyad", "MAHREZ"],
    ["AOUAR Houssem", "AOUAR"],
    ["GOUIRI Amine", "GOUIRI"],
    ["CHAIBI Fares", "CHAIBI"],
    ["HADJ MOUSSA Anis", "HADJ MOUSSA"],
    ["BENBOUALI Nadhir", "BENBOUALI"],
    ["HADJAM Jaouen", "HADJAM"],
    ["BOUDAOUI Hicham", "BOUDAOUI"],
    ["AIT-NOURI Rayan", "AIT NOURI"],
    ["BENBOT Oussama", "BENBOT"],
    ["BELGHALI Ra«k", "BELGHALI"],
    ["AMOURA Mohamed", "AMOURA"],
    ["BENTALEB Nabil", "BENTALEB"],
    ["BOULBINA Adil", "BOULBINA"],
    ["BENSEBAINI Ramy", "BENSEBAINI"],
    ["MAZA Ibrahim", "MAZA"],
    ["ZIDANE Luca", "ZIDANE"],
    ["TITRAOUI Yassine", "TITRAOUI"],
    ["GHEDJEMIS Fares", "GHEDJEMIS"],
    ["CHERGUI Samir", "CHERGUI"],
  ],
  "ec": [
    ["GALINDEZ Hernan", "GALINDEZ"],
    ["TORRES Felix", "TORRES"],
    ["HINCAPIE Piero", "HINCAPIE"],
    ["ORDONEZ Joel", "ORDÓÑEZ"],
    ["ALCIVAR Jordy", "ALCIVAR"],
    ["PACHO Willian", "PACHO"],
    ["ESTUPINAN Pervis", "ESTUPIÑÁN"],
    ["VALENCIA Anthony", "A. VALENCIA"],
    ["YEBOAH John", "YEBOAH ZAMORA"],
    ["PAEZ Kendry", "KENDRY"],
    ["RODRIGUEZ Kevin", "RODRIGUEZ"],
    ["RAMIREZ Moises", "RAMÍREZ"],
    ["VALENCIA Enner", "E. VALENCIA"],
    ["MINDA Alan", "MINDA"],
    ["VITE Pedro", "VITE"],
    ["CAICEDO Jordy", "J. CAICEDO"],
    ["PRECIADO Angelo", "PRECIADO"],
    ["CASTILLO Denil", "CASTILLO"],
    ["PLATA Gonzalo", "PLATA"],
    ["ANGULO Nilson", "ANGULO"],
    ["FRANCO Alan", "FRANCO"],
    ["VALLE Gonzalo", "VALLE"],
    ["CAICEDO Moises", "M. CAICEDO"],
    ["AREVALO Jeremy", "AREVALO"],
    ["POROZO Jackson", "POROZO"],
    ["MEDINA Yaimar", "MEDINA"],
  ],
  "eg": [
    ["MOHAMED ELSHENAWY", "M. ELSHENAWY"],
    ["YASSER IBRAHIM", "YASSER"],
    ["MOHAMED HANY", "M. HANY"],
    ["HOSSAM ABDELMAGUID", "HOSSAM"],
    ["RAMY RABIA", "R. RABIAA"],
    ["MOHAMED ABDELMONEIM", "M. ABDELMONIEM"],
    ["TREZEGUET", "M. TREZEGUET"],
    ["EMAM ASHOUR", "E. ASHOUR"],
    ["HAMZA ABDELKARIM", "ABDELKARIM"],
    ["MOHAMED SALAH", "M. SALAH"],
    ["MOSTAFA ZICO", "ZICO"],
    ["HAISSEM HASSAN", "H. HASSAN"],
    ["AHMED FATOUH", "A. FATOUH"],
    ["HAMDY FATHY", "H. FATHY"],
    ["KARIM HAFEZ", "K. HAFEZ"],
    ["MAHDY SOLIMAN", "M. SOLIMAN"],
    ["MOHANAD LASHIN", "M. LASHIN"],
    ["NABIL DONGA", "DONGA"],
    ["MARAWAN ATTIA", "M. ATTIA"],
    ["IBRAHIM ADEL", "I. ADEL"],
    ["MAHMOUD SABER", "M. SABER"],
    ["OMAR MARMOUSH", "MARMOUSH"],
    ["MOSTAFA SHOUBIR", "SHOUBIR"],
    ["TAREK ALAA", "T. ALAA"],
    ["ZIZO", "ZIZO"],
    ["MOHAMED ALAA", "M. ALAA"],
  ],
  "es": [
    ["RAYA David", "RAYA"],
    ["PUBILL Marc", "MARC PUBILL"],
    ["GRIMALDO Alex", "GRIMALDO"],
    ["GARCIA Eric", "ERIC"],
    ["LLORENTE Marcos", "M. LLORENTE"],
    ["MERINO Mikel", "MERINO"],
    ["TORRES Ferran", "FERRAN"],
    ["RUIZ Fabian", "FABIÁN"],
    ["GAVI", "GAVI"],
    ["OLMO Dani", "OLMO"],
    ["PINO Yeremy", "YEREMY"],
    ["PORRO Pedro", "PEDRO PORRO"],
    ["GARCIA Joan", "JOAN GARCIA"],
    ["LAPORTE Aymeric", "LAPORTE"],
    ["BAENA Alex", "ALEX B."],
    ["RODRI", "RODRIGO"],
    ["WILLIAMS Nico", "WILLIAMS JR."],
    ["ZUBIMENDI Martin", "ZUBIMENDI"],
    ["YAMAL Lamine", "LAMINE YAMAL"],
    ["PEDRI", "PEDRI"],
    ["OYARZABAL Mikel", "OYARZABAL"],
    ["CUBARSI Pau", "CUBARSÍ"],
    ["SIMON Unai", "UNAI SIMÓN"],
    ["CUCURELLA Marc", "CUCURELLA"],
    ["MUNOZ Victor", "VICTOR M.V."],
    ["IGLESIAS Borja", "B. IGLESIAS"],
  ],
  "fr": [
    ["SAMBA Brice", "SAMBA"],
    ["GUSTO Malo", "GUSTO"],
    ["DIGNE Lucas", "DIGNE"],
    ["UPAMECANO Dayot", "UPAMECANO"],
    ["KOUNDE Jules", "KOUNDE"],
    ["KONE Manu", "KONE"],
    ["DEMBELE Ousmane", "DEMBELE"],
    ["TCHOUAMENI Aurelien", "TCHOUAMENI"],
    ["THURAM Marcus", "THURAM"],
    ["MBAPPE Kylian", "MBAPPE"],
    ["OLISE Michael", "OLISE"],
    ["BARCOLA Bradley", "BARCOLA"],
    ["KANTE Ngolo", "KANTE"],
    ["RABIOT Adrien", "RABIOT"],
    ["KONATE Ibrahima", "KONATE"],
    ["MAIGNAN Mike", "MAIGNAN"],
    ["SALIBA William", "SALIBA"],
    ["ZAIRE-EMERY Warren", "ZAIRE-EMERY"],
    ["HERNANDEZ Theo", "T. HERNANDEZ"],
    ["DOUE Desire", "DOUE"],
    ["HERNANDEZ Lucas", "L. HERNANDEZ"],
    ["MATETA Jean-Philippe", "MATETA"],
    ["RISSER Robin", "RISSER"],
    ["CHERKI Rayan", "CHERKI"],
    ["AKLIOUCHE Maghnes", "AKLIOUCHE"],
    ["LACROIX Maxence", "LACROIX"],
  ],
  "gb-eng": [
    ["PICKFORD Jordan", "PICKFORD"],
    ["KONSA Ezri", "KONSA"],
    ["OREILLY Nico", "O'REILLY"],
    ["RICE Declan", "RICE"],
    ["STONES John", "STONES"],
    ["GUEHI Marc", "GUÉHI"],
    ["SAKA Bukayo", "SAKA"],
    ["ANDERSON Elliot", "ANDERSON"],
    ["KANE Harry", "KANE"],
    ["BELLINGHAM Jude", "BELLINGHAM"],
    ["RASHFORD Marcus", "RASHFORD"],
    ["CHALOBAH Trevoh", "CHALOBAH"],
    ["HENDERSON Dean", "D. HENDERSON"],
    ["HENDERSON Jordan", "HENDERSON"],
    ["BURN Dan", "BURN"],
    ["MAINOO Kobbie", "MAINOO"],
    ["ROGERS Morgan", "ROGERS"],
    ["GORDON Anthony", "GORDON"],
    ["WATKINS Ollie", "WATKINS"],
    ["MADUEKE Noni", "MADUEKE"],
    ["EZE Eberechi", "EZE"],
    ["TONEY Ivan", "TONEY"],
    ["TRAFFORD James", "TRAFFORD"],
    ["JAMES Reece", "JAMES"],
    ["SPENCE Djed", "SPENCE"],
    ["QUANSAH Jarell", "QUANSAH"],
  ],
  "gb-sct": [
    ["GUNN Angus", "GUNN"],
    ["HICKEY Aaron", "HICKEY"],
    ["ROBERTSON Andy", "ROBERTSON"],
    ["McTOMINAY Scott", "MCTOMINAY"],
    ["HANLEY Grant", "HANLEY"],
    ["TIERNEY Kieran", "TIERNEY"],
    ["McGINN John", "MCGINN"],
    ["FLETCHER Tyler", "FLETCHER"],
    ["DYKES Lyndon", "DYKES"],
    ["ADAMS Che", "ADAMS"],
    ["CHRISTIE Ryan", "CHRISTIE"],
    ["KELLY Liam", "KELLY"],
    ["HENDRY Jack", "HENDRY"],
    ["STEWART Ross", "STEWART"],
    ["SOUTTAR John", "SOUTTAR"],
    ["HYAM Dominic", "HYAM"],
    ["GANNON-DOAK Ben", "GANNON DOAK"],
    ["HIRST George", "HIRST"],
    ["FERGUSON Lewis", "FERGUSON"],
    ["SHANKLAND Lawrence", "SHANKLAND"],
    ["GORDON Craig", "GORDON"],
    ["PATTERSON Nathan", "PATTERSON"],
    ["McLEAN Kenny", "MCLEAN"],
    ["RALSTON Anthony", "RALSTON"],
    ["CURTIS Findlay", "CURTIS"],
    ["McKENNA Scott", "MCKENNA"],
  ],
  "gh": [
    ["ZIGI Lawrence Ati", "ZIGI"],
    ["SEIDU Alidu", "ALIDU SEIDU"],
    ["YIRENKYI Caleb", "YIRENKYI"],
    ["ADJETEY Jonas", "ADJETEY"],
    ["PARTEY Thomas", "PARTEY"],
    ["MUMIN Abdul", "A. MUMIN"],
    ["FATAWU Abdul", "A. FATAWU"],
    ["SIBO Kwasi", "SIBO"],
    ["AYEW Jordan", "J. AYEW"],
    ["THOMAS-ASANTE Brandon", "ASANTE"],
    ["SEMENYO Antoine", "SEMENYO"],
    ["ANANG Joseph", "ANANG"],
    ["BONSU BAAH Christopher", "BONSU BAAH"],
    ["MENSAH Gideon", "MENSAH"],
    ["OWUSU Elisha", "OWUSU"],
    ["ASARE Benjamin", "B. ASARE"],
    ["RAHMAN Baba", "BABA"],
    ["OPOKU Jerome", "OPOKU"],
    ["WILLIAMS Inaki", "WILLIAMS"],
    ["BOAKYE Augustine", "BOAKYE"],
    ["OPPONG Kojo Peprah", "OPPONG"],
    ["SULEMANA Kamaldeen", "KAMALDEEN"],
    ["LUCKASSEN Derrick", "LUCKASSEN"],
    ["NUAMAH Ernest", "NUAMAH"],
    ["ADU Prince", "PRINCE"],
    ["SENAYA Marvin", "SENEYA"],
  ],
  "hr": [
    ["LIVAKOVIC Dominik", "LIVAKOVIĆ"],
    ["STANISIC Josip", "STANIŠIĆ"],
    ["PONGRACIC Marin", "PONGRAČIĆ"],
    ["GVARDIOL Josko", "GVARDIOL"],
    ["CALETA-CAR Duje", "ĆALETA-CAR"],
    ["SUTALO Josip", "ŠUTALO"],
    ["MORO Nikola", "MORO"],
    ["KOVACIC Mateo", "KOVAČIĆ"],
    ["KRAMARIC Andrej", "KRAMARIĆ"],
    ["MODRIC Luka", "MODRIĆ"],
    ["BUDIMIR Ante", "BUDIMIR"],
    ["PANDUR Ivor", "PANDUR"],
    ["VLASIC Nikola", "VLAŠIĆ"],
    ["PERISIC Ivan", "PERIŠIĆ"],
    ["PASALIC Mario", "PAŠALIĆ"],
    ["BATURINA Martin", "BATURINA"],
    ["SUCIC Petar", "P. SUČIĆ"],
    ["JAKIC Kristijan", "JAKIĆ"],
    ["FRUK Toni", "FRUK"],
    ["MATANOVIC Igor", "MATANOVIĆ"],
    ["SUCIC Luka", "SUČIĆ"],
    ["VUSKOVIC Luka", "VUŠKOVIĆ"],
    ["KOTARSKI Dominik", "KOTARSKI"],
    ["PASALIC Marco", "M. PAŠALIĆ"],
    ["ERLIC Martin", "ERLIĆ"],
    ["MUSA Petar", "MUSA"],
  ],
  "ht": [
    ["PLACIDE Johny", "PLACIDE"],
    ["ARCUS Carlens", "ARCUS"],
    ["THERMONCY Keeto", "THERMONCY"],
    ["ADE Ricardo", "ADE"],
    ["DELCROIX Hannes", "DELCROIX"],
    ["SAINTE Carl", "SAINTE"],
    ["ETIENNE Derrick", "ETIENNE JR"],
    ["EXPERIENCE Martin", "EXPERIENCE"],
    ["NAZON Duckens", "NAZON"],
    ["BELLEGARDE Jean-Ricner", "BELLEGARDE"],
    ["DEEDSON Louicius", "LOUICIUS"],
    ["PIERRE Alexandre", "A. PIERRE"],
    ["LACROIX Markhus", "LACROIX"],
    ["METUSALA Garven", "METUSALA"],
    ["PROVIDENCE Ruben", "PROVIDENCE"],
    ["JOSEPH Lenny", "JOSEPH"],
    ["JEAN JACQUES Danley", "JEAN-JACQUES"],
    ["ISIDOR Wilson", "ISIDOR"],
    ["FORTUNE Yassin", "FORTUNE"],
    ["PIERROT Frantzdy", "PIERROT"],
    ["CASIMIR Josue", "CASIMIR"],
    ["DUVERNE Jean-Kevin", "DUVERNE"],
    ["DUVERGER Josue", "DUVERGER"],
    ["PAUGAIN Wilguens", "PAUGAIN"],
    ["SIMON Dominique", "SIMON"],
    ["PIERRE Woodensky", "W. PIERRE"],
  ],
  "iq": [
    ["FAHAD TALIB", "FAHAD"],
    ["REBIN SULAKA", "REBIN"],
    ["HUSSEIN ALI", "HUSSEIN"],
    ["ZAID TAHSEEN", "ZAID T."],
    ["AKAM HASHIM", "AKAM"],
    ["MUNAF YOUNUS", "MUNAF"],
    ["YOUSSEF AMYN", "YOUSSEF"],
    ["IBRAHIM BAYESH", "IBRAHIM"],
    ["ALI ALHAMADI", "AL-HAMADI"],
    ["MOHANAD ALI", "MOHANAD"],
    ["AHMED QASEM", "AHMED Q."],
    ["JALAL HASSAN", "JALAL"],
    ["ALI YOUSIF", "ALI Y."],
    ["ZIDANE IQBAL", "Z. IQBAL"],
    ["AHMED MAKNAZI", "AHMED H."],
    ["AMIR ALAMMARI", "AL-AMMARI"],
    ["ALI JASIM", "ALI J."],
    ["AYMEN HUSSEIN", "AYMEN"],
    ["KEVIN YAKOB", "K. YAKOB"],
    ["AIMAR SHER", "AIMAR"],
    ["MARKO FARJI", "MARKO"],
    ["AHMED BASIL", "AHMED B."],
    ["MERCHAS DOSKI", "DOSKI"],
    ["ZAID ISMAEL", "ZAID I."],
    ["MUSTAFA SAADOON", "MUSTAFA"],
    ["FRANS PUTROS", "FRANS"],
  ],
  "ir": [
    ["BEIRANVAND Alireza", "BEIRANVAND"],
    ["HARDANI Saleh", "SALEH"],
    ["HAJISAFI Ehsan", "E. HAJISAFI"],
    ["KHALILZADEH Shoja", "SHOJA"],
    ["MOHAMMADI Milad", "M. MOHAMMADI"],
    ["EZATOLAHI Saeid", "S. EZATOLAHI"],
    ["JAHANBAKHSH Alireza", "A. JAHANBAKHSH"],
    ["MOHEBBI Mohammad", "M. MOHEBBI"],
    ["TAREMI Mehdi", "TAREMI"],
    ["GHAYEDI Mehdi", "MEHDI GHAYEDI"],
    ["ALIPOUR Ali", "A. ALIPOUR"],
    ["NIAZMAND Payam", "PAYAM"],
    ["KANANI Hossein", "KANANI"],
    ["GHODDOS Saman", "GHODDOS"],
    ["CHESHMI Roozbeh", "ROOZBEH"],
    ["TORABI Mehdi", "M. TORABI"],
    ["YOUSEFI Arya", "ARYA"],
    ["HOSSEINZADEH Amirhossein", "AMIRHOSSEIN"],
    ["NEMATI Ali", "ALI"],
    ["MOGHANLOO Shahriyar", "SHAHRIYAR"],
    ["GHORBANI Mohammad", "MOHAMMAD"],
    ["HOSSEINI Hossein", "HOSSEINI"],
    ["REZAEIAN Ramin", "RAMIN"],
    ["DARGAHI Dennis", "DARGAHI"],
    ["IRI Danial", "DANIAL"],
    ["RAZAGHINIA Amirmohammad", "RAZAGH"],
  ],
  "jo": [
    ["YAZEED ABULAILA", "YAZEED"],
    ["MOHAMMAD ABUHASHEESH", "ABU HASHEESH"],
    ["ABDALLAH NASIB", "NASIB"],
    ["HUSAM ABUDAHAB", "ABU DAHAB"],
    ["YAZAN ALARAB", "ALARAB"],
    ["AMER JAMOUS", "JAMOUS"],
    ["MOHAMMAD ABUZRAIQ", "ABU ZRAIQ"],
    ["NOOR ALRAWABDEH", "ALRAWABDEH"],
    ["ALI OLWAN", "OLWAN"],
    ["MOUSA ALTAMARI", "ALTAMARI"],
    ["ODEH FAKHOURY", "ODEH"],
    ["NOUR BANIATEYAH", "BANI ATEYAH"],
    ["MAHMOUD ALMARDI", "ALMARDI"],
    ["RAJAEI AYED", "RAJA'EI"],
    ["IBRAHIM SADEH", "SA'DEH"],
    ["MOHAMMAD ABUALNADI", "ABU ALNADI"],
    ["SALEEM OBAID", "SALEEM"],
    ["MOHAMMAD ABUGHOUSH", "ABU GHOUSH"],
    ["SAED ALROSAN", "SA'ED"],
    ["MOHANNAD ABUTAHA", "ABU TAHA"],
    ["NIZAR ALRASHDAN", "NIZAR"],
    ["ABDALLAH ALFAKHORI", "ALFAKHORI"],
    ["EHSAN HADDAD", "EHSAN"],
    ["ALI AZAIZEH", "AZAIZEH"],
    ["MOHAMMAD ALDAOUD", "ALDAOUD"],
    ["ANAS BADAWI", "BADAWI"],
  ],
  "jp": [
    ["SUZUKI Zion", "SUZUKI"],
    ["SUGAWARA Yukinari", "SUGAWARA"],
    ["TANIGUCHI Shogo", "TANIGUCHI"],
    ["ITAKURA Kou", "ITAKURA"],
    ["NAGATOMO Yuto", "NAGATOMO"],
    ["MACHINO Shuto", "MACHINO"],
    ["TANAKA Ao", "TANAKA"],
    ["KUBO Takefusa", "KUBO"],
    ["GOTO Keisuke", "GOTO"],
    ["DOAN Ritsu", "DOAN"],
    ["MAEDA Daizen", "DAIZEN"],
    ["OSAKO Keisuke", "OSAKO"],
    ["NAKAMURA Keito", "NAKAMURA"],
    ["ITO Junya", "ITO"],
    ["KAMADA Daichi", "KAMADA"],
    ["WATANABE Tsuyoshi", "WATANABE"],
    ["SUZUKI Yuito", "Y. SUZUKI"],
    ["UEDA Ayase", "AYASE"],
    ["OGAWA Koki", "OGAWA"],
    ["SEKO Ayumu", "SEKO"],
    ["ITO Hiroki", "H. ITO"],
    ["TOMIYASU Takehiro", "TOMIYASU"],
    ["HAYAKAWA Tomoki", "HAYAKAWA"],
    ["SANO Kaishu", "SANO"],
    ["SUZUKI Junnosuke", "J. SUZUKI"],
    ["SHIOGAI Kento", "SHIOGAI"],
  ],
  "kr": [
    ["KIM Seunggyu", "SEUNGGYU"],
    ["LEE Hanbeom", "HANBEOM"],
    ["LEE Gihyuk", "GIHYUK"],
    ["KIM Minjae", "MINJAE"],
    ["KIM Taehyeon", "TAEHYEON"],
    ["HWANG Inbeom", "INBEOM"],
    ["SON Heungmin", "HEUNGMIN"],
    ["PAIK Seungho", "SEUNGHO"],
    ["CHO Guesung", "GUESUNG"],
    ["LEE Jaesung", "JAESUNG"],
    ["HWANG Heechan", "HEECHAN"],
    ["SONG Bumkeun", "BUMKEUN"],
    ["LEE Taeseok", "TAESEOK"],
    ["CHO Wije", "WIJE"],
    ["KIM Moonhwan", "MOONHWAN"],
    ["PARK Jinseob", "JINSEOB"],
    ["BAE Junho", "JUNHO"],
    ["OH Hyeongyu", "HYEONGYU"],
    ["LEE Kangin", "KANGIN"],
    ["YANG Hyunjun", "HYUNJUN"],
    ["JO Hyeonwoo", "HYEONWOO"],
    ["SEOL Youngwoo", "YOUNGWOO"],
    ["CASTROP Jens", "JENS"],
    ["KIM Jingyu", "JINGYU"],
    ["EOM Jisung", "JISUNG"],
    ["LEE Donggyeong", "DONGGYEONG"],
  ],
  "ma": [
    ["BOUNOU Yassine", "BONO"],
    ["HAKIMI Achraf", "HAKIMI"],
    ["MAZRAOUI Noussair", "MAZRAOUI"],
    ["AMRABAT Sofyan", "AMRABAT"],
    ["SAADANE Marwane", "SAADANE"],
    ["BOUADDI Ayyoub", "BOUADDI"],
    ["TALBI Chemsdine", "TALBI"],
    ["OUNAHI Azzedine", "OUNAHI"],
    ["RAHIMI Sou«ane", "RAHIMI"],
    ["DIAZ Brahim", "BRAHIM"],
    ["SAIBARI Ismael", "SAIBARI"],
    ["EL KAJOUI Munir", "EL KAJOUI"],
    ["EL OUAHDI Zakaria", "EL OUAHDI"],
    ["DIOP Issa", "ISSA"],
    ["EL MOURABET Samir", "EL MOURABET"],
    ["YASSINE Gessime", "YASSINE"],
    ["SBAI Amine", "SBAÏ"],
    ["RIAD Chadi", "RIAD"],
    ["BELAMMARI Youssef", "BELAMMARI"],
    ["EL KAABI Ayoub", "EL KAABI"],
    ["AMAIMOUNI Ayoube", "AMAIMOUNI"],
    ["TAGNAOUTI Ahmed Reda", "TAGNAOUTI"],
    ["EL KHANNOUSS Bilal", "EL KHANNOUSS"],
    ["EL AYNAOUI Neil", "EL AYNAOUI"],
    ["HALHAL Redouane", "HALHAL"],
    ["SALAH EDDINE Anass", "SALAH-EDDINE"],
  ],
  "mx": [
    ["RANGEL Raul", "R. RANGEL"],
    ["SANCHEZ Jorge", "J. SÁNCHEZ"],
    ["MONTES Cesar", "C. MONTES"],
    ["ALVAREZ Edson", "E. ÁLVAREZ"],
    ["VASQUEZ Johan", "J. VÁSQUEZ"],
    ["LIRA Erik", "E. LIRA"],
    ["ROMO Luis", "L. ROMO"],
    ["FIDALGO Alvaro", "FIDALGO"],
    ["JIMENEZ Raul", "RAÚL"],
    ["VEGA Alexis", "A. VEGA"],
    ["GIMENEZ Santiago", "S. GIMENEZ"],
    ["ACEVEDO Carlos", "C. ACEVEDO"],
    ["OCHOA Guillermo", "G. OCHOA"],
    ["GONZALEZ Armando", "A. GONZÁLEZ"],
    ["REYES Israel", "I. REYES"],
    ["QUINONES Julian", "J. QUIÑONES"],
    ["PINEDA Orbelin", "ORBELÍN"],
    ["VARGAS Obed", "O. VARGAS"],
    ["MORA Gilberto", "G. MORA"],
    ["CHAVEZ Mateo", "M. CHÁVEZ"],
    ["HUERTA Cesar", "C. HUERTA"],
    ["MARTINEZ Guillermo", "G. MARTÍNEZ"],
    ["GALLARDO Jesus", "J. GALLARDO"],
    ["CHAVEZ Luis", "L. CHÁVEZ"],
    ["ALVARADO Roberto", "R. ALVARADO"],
    ["GUTIERREZ Brian", "B. GUTIÉRREZ"],
  ],
  "nl": [
    ["VERBRUGGEN Bart", "VERBRUGGEN"],
    ["GEERTRUIDA Lutsharel", "GEERTRUIDA"],
    ["DE ROON Marten", "DE ROON"],
    ["VAN DIJK Virgil", "VIRGIL"],
    ["AKE Nathan", "AKÉ"],
    ["VAN HECKE Jan Paul", "VAN HECKE"],
    ["KLUIVERT Justin", "KLUIVERT"],
    ["GRAVENBERCH Ryan", "GRAVENBERCH"],
    ["WEGHORST Wout", "WEGHORST"],
    ["DEPAY Memphis", "MEMPHIS"],
    ["GAKPO Cody", "GAKPO"],
    ["WIEFFER Mats", "WIEFFER"],
    ["ROEFS Robin", "ROEFS"],
    ["REIJNDERS Tijjani", "REIJNDERS"],
    ["VAN DE VEN Micky", "VAN DE VEN"],
    ["TIL Guus", "TIL"],
    ["LANG Noa", "LANG"],
    ["MALEN Donyell", "MALEN"],
    ["BROBBEY Brian", "BROBBEY"],
    ["KOOPMEINERS Teun", "KOOPMEINERS"],
    ["DE JONG Frenkie", "F. DE JONG"],
    ["DUMFRIES Denzel", "DUMFRIES"],
    ["FLEKKEN Mark", "FLEKKEN"],
    ["SUMMERVILLE Crysencio", "SUMMERVILLE"],
    ["HATO Jorrel", "HATO"],
    ["TIMBER Quinten", "Q. TIMBER"],
  ],
  "no": [
    ["NYLAND Orjan", "NYLAND"],
    ["THORSBY Morten", "THORSBY"],
    ["AJER Kristoffer", "VASSBAKK AJER"],
    ["OSTIGARD Leo", "ØSTIGÅRD"],
    ["MOLLER WOLFE David", "MØLLER WOLFE"],
    ["BERG Patrick", "BERG"],
    ["SORLOTH Alexander", "SØRLOTH"],
    ["BERGE Sander", "BERGE"],
    ["HAALAND Erling", "BRAUT HAALAND"],
    ["ODEGAARD Martin", "ØDEGAARD"],
    ["STRAND LARSEN Jorgen", "STRAND LARSEN"],
    ["TANGVIK Sander", "TANGVIK"],
    ["SELVIK Egil", "SELVIK"],
    ["AURSNES Fredrik", "AURSNES"],
    ["BJORKAN Fredrik Andre", "BJØRKAN"],
    ["HOLMGREN PEDERSEN Marcus", "HOLMGREN"],
    ["HEGGEM Torbjorn", "HEGGEM"],
    ["THORSTVEDT Kristian", "THORSTVEDT"],
    ["AASGAARD Thelo", "AASGAARD"],
    ["NUSA Antonio", "NUSA"],
    ["SCHJELDERUP Andreas", "SCHJELDERUP"],
    ["BOBB Oscar", "BOBB"],
    ["HAUGE Jens Petter", "HAUGE"],
    ["LANGAS Sondre", "LANGÅS"],
    ["FALCHENER Henrik", "FALCHENER"],
    ["RYERSON Julian", "RYERSON"],
  ],
  "nz": [
    ["CROCOMBE Max", "CROCOMBE"],
    ["PAYNE Tim", "PAYNE"],
    ["DE VRIES Francis", "DE VRIES"],
    ["BINDON Tyler", "BINDON"],
    ["BOXALL Michael", "BOXALL"],
    ["BELL Joe", "BELL"],
    ["ROGERSON Logan", "ROGERSON"],
    ["STAMENIC Marko", "STAMENIC"],
    ["WOOD Chris", "WOOD"],
    ["SINGH Sarpreet", "SINGH"],
    ["JUST Elijah", "JUST"],
    ["PAULSEN Alex", "PAULSEN"],
    ["CACACE Liberato", "CACACE"],
    ["RUFER Alex", "RUFER"],
    ["PIJNAKER Nando", "PIJNAKER"],
    ["SURMAN Finn", "SURMAN"],
    ["BARBAROUSES Kosta", "BARBAROUSES"],
    ["WAINE Ben", "WAINE"],
    ["OLD Ben", "OLD"],
    ["McCOWATT Callum", "MCCOWATT"],
    ["RANDALL Jesse", "RANDALL"],
    ["WOUD Michael", "WOUD"],
    ["THOMAS Ryan", "THOMAS"],
    ["ELLIOT Callan", "ELLIOT"],
    ["BAYLISS Lachlan", "BAYLISS"],
    ["SMITH Tommy", "SMITH"],
  ],
  "pa": [
    ["MEJIA Luis", "MEJIA"],
    ["BLACKMAN Cesar", "BLACKMAN"],
    ["CORDOBA Jose", "CORDOBA"],
    ["ESCOBAR Fidel", "F. ESCOBAR"],
    ["FARINA Edgardo", "FARIÑA"],
    ["MARTINEZ Cristian", "MARTÍNEZ"],
    ["RODRIGUEZ Jose Luis", "J.L. RODRÍGUEZ"],
    ["CARRASQUILLA Adalberto", "CARRASQUILLA"],
    ["RODRIGUEZ Tomas", "T. RODRÍGUEZ"],
    ["DIAZ Ismael", "ISMAEL"],
    ["BARCENAS Edgar Yoel", "BÁRCENAS"],
    ["SAMUDIO Cesar", "SAMUDIO"],
    ["RAMOS Jiovany", "RAMOS"],
    ["HARVEY Carlos", "HARVEY"],
    ["DAVIS Eric", "DAVIS"],
    ["ANDRADE Andres", "ANDRADE"],
    ["FAJARDO Jose", "FAJARDO"],
    ["WATERMAN Cecilio", "WATERMAN"],
    ["QUINTERO Alberto", "QUINTERO"],
    ["GODOY Anibal", "GODOY"],
    ["YANIS Cesar", "YANIS"],
    ["MOSQUERA Orlando", "MOSQUERA"],
    ["MURILLO Amir", "A. MURILLO"],
    ["LONDONO Azarias", "LONDOÑO"],
    ["MILLER Roderick", "MILLER"],
    ["GUTIERREZ Jorge", "GUTIÉRREZ"],
  ],
  "pt": [
    ["DIOGO COSTA", "DIOGO COSTA"],
    ["NELSON SEMEDO", "N. SEMEDO"],
    ["RUBEN DIAS", "RÚBEN DIAS"],
    ["TOMAS ARAUJO", "TOMÁS A."],
    ["DIOGO DALOT", "DALOT"],
    ["MATHEUS NUNES", "MATHEUS N."],
    ["CRISTIANO RONALDO", "RONALDO"],
    ["BRUNO FERNANDES", "B. FERNANDES"],
    ["GONCALO RAMOS", "G. RAMOS"],
    ["BERNARDO SILVA", "BERNARDO"],
    ["JOAO FELIX", "JOÃO FÉLIX"],
    ["JOSE SA", "JOSÉ SÁ"],
    ["RENATO VEIGA", "RENATO VEIGA"],
    ["GONCALO INACIO", "G. INÁCIO"],
    ["JOAO NEVES", "JOÃO NEVES"],
    ["FRANCISCO TRINCAO", "TRINCÃO"],
    ["RAFAEL LEAO", "RAFA LEÃO"],
    ["PEDRO NETO", "NETO"],
    ["GONCALO GUEDES", "G. GUEDES"],
    ["JOAO CANCELO", "JOÃO CANCELO"],
    ["RUBEN NEVES", "R. NEVES"],
    ["RUI SILVA", "RUI SILVA"],
    ["VITINHA", "VITINHA"],
    ["SAMU COSTA", "SAMU"],
    ["NUNO MENDES", "N. MENDES"],
    ["FRANCISCO CONCEICAO", "F. CONCEIÇÃO"],
  ],
  "py": [
    ["FERNANDEZ Gatito", "FERNÁNDEZ"],
    ["VELAZQUEZ Gustavo", "VELÁZQUEZ"],
    ["ALDERETE Omar", "ALDERETE"],
    ["CACERES Juan Jose", "CÁCERES"],
    ["BALBUENA Fabian", "BALBUENA"],
    ["ALONSO Junior", "ALONSO"],
    ["SOSA Ramon", "SOSA"],
    ["GOMEZ Diego", "D. GÓMEZ"],
    ["SANABRIA Antonio", "SANABRIA"],
    ["ALMIRON Miguel", "ALMIRÓN"],
    ["MAURICIO", "MAURICIO"],
    ["GILL Orlando", "O. GILL"],
    ["CANALE Jose", "CANALE"],
    ["CUBAS Andres", "CUBAS"],
    ["GOMEZ Gustavo", "G. GÓMEZ"],
    ["BOBADILLA Damian", "BOBADILLA"],
    ["ROMERO GAMARRA Alejandro", "R. GAMARRA"],
    ["ARCE Alex", "ARCE"],
    ["ENCISO Julio", "ENCISO"],
    ["OJEDA Braian", "OJEDA"],
    ["AVALOS Gabriel", "AVALOS"],
    ["OLVEIRA Gaston", "OLVEIRA"],
    ["GALARZA Matias", "GALARZA"],
    ["CABALLERO Gustavo", "CABALLERO"],
    ["PITTA Isidro", "PITTA"],
    ["MAIDANA Alexandro", "MAIDANA"],
  ],
  "qa": [
    ["MAHMOUD ABUNADA", "ABUNADA"],
    ["PEDRO MIGUEL", "PEDRO"],
    ["LUCAS MENDES", "L.MENDES"],
    ["ISSA LAYE", "GUEYE"],
    ["JASSEM GABER", "JASSEM"],
    ["ABDULAZIZ HATEM", "A. AZIZ"],
    ["AHMED ALAAELDIN", "ALAAELDIN"],
    ["EDMILSON JUNIOR", "EDMILSON JR."],
    ["MOHAMMED MUNTARI", "MUNTARI"],
    ["HASSAN ALHAYDOS", "ALHAYDOS"],
    ["AKRAM AFIF", "AFIF"],
    ["KARIM BOUDIAF", "KARIM"],
    ["AYOUB ALOUI", "AYOUB"],
    ["HOMAM AHMED", "HOMAM"],
    ["YUSUF ABDURISAG", "YUSUF"],
    ["BOUALEM KHOUKHI", "KHOUKHI"],
    ["AHMED ALGANEHI", "A. ALGANEHI"],
    ["SULTAN ALBRAKE", "SULTAN"],
    ["ALMOEZ ALI", "ALMOEZ"],
    ["AHMED FATHY", "A. FATHY"],
    ["SALAH ZAKARIA", "SALAH"],
    ["MESHAAL BARSHAM", "BARSHAM"],
    ["ASSIM MADIBO", "MADIBO"],
    ["TAHSIN MOHAMMED", "TAHSIN"],
    ["ALHASHMI ALHUSSEIN", "ALHASHMI"],
    ["MOHAMED MANAI", "MANAI"],
  ],
  "sa": [
    ["NAWAF ALAQIDI", "ALAQIDI"],
    ["ALI MAJRASHI", "MAJRASHI"],
    ["ALI LAJAMI", "LAJAMI"],
    ["ABDULELAH ALAMRI", "ALAMRI"],
    ["HASSAN ALTAMBAKTI", "ALTAMBAKTI"],
    ["NASSER ALDAWSARI", "NASSER"],
    ["MUSAB ALJUWAYR", "MUSAB"],
    ["AIMAN YAHYA", "AIMAN"],
    ["FERAS ALBRIKAN", "FERAS"],
    ["SALEM ALDAWSARI", "SALEM"],
    ["SALEH ALSHEHRI", "ALSHEHRI"],
    ["SAUD ABDULHAMID", "SAUD"],
    ["NAWAF BU WASHL", "NAWAF"],
    ["HASSAN KADISH", "KADISH"],
    ["ABDULLAH ALKHAIBARI", "ALKHAIBARI"],
    ["ZIYAD ALJOHANI", "ZIYAD"],
    ["KHALID ALGHANNAM", "KHALID"],
    ["ALA ALHAJJI", "ALHAJJI"],
    ["ABDULLAH ALHAMDDAN", "ALHAMDDAN"],
    ["SULTAN MANDASH", "MANDASH"],
    ["MOHAMMED ALOWAIS", "ALOWAIS"],
    ["AHMED ALKASSAR", "ALKASSAR"],
    ["MOHAMED KANNO", "KANNO"],
    ["MOTEB ALHARBI", "MOTEB"],
    ["JEHAD THIKRI", "JEHAD"],
    ["MOHAMMED ABU ALSHAMAT", "MOHAMMED"],
  ],
  "se": [
    ["WIDELL ZETTERSTROM Jacob", "ZETTERSTRÖM"],
    ["LAGERBIELKE Gustaf", "LAGERBIELKE"],
    ["LINDELOF Victor", "LINDELÖF"],
    ["HIEN Isak", "HIEN"],
    ["GUDMUNDSSON Gabriel", "GUDMUNDSSON"],
    ["JOHANSSON Herman", "H. JOHANSSON"],
    ["BERGVALL Lucas", "BERGVALL"],
    ["SVENSSON Daniel", "SVENSSON"],
    ["ISAK Alexander", "ISAK"],
    ["NYGREN Benjamin", "NYGREN"],
    ["ELANGA Anthony", "ELANGA"],
    ["JOHANSSON Viktor", "V. JOHANSSON"],
    ["SEMA Ken", "SEMA"],
    ["EKDAL Hjalmar", "EKDAL"],
    ["STARFELT Carl", "STARFELT"],
    ["KARLSTROM Jesper", "KARLSTRÖM"],
    ["GYOKERES Viktor", "GYÖKERES"],
    ["AYARI Yasin", "AYARI"],
    ["SVANBERG Mattias", "SVANBERG"],
    ["SMITH Eric", "SMITH"],
    ["BERNHARDSSON Alexander", "BERNHARDSSON"],
    ["ZENELI Besfort", "ZENELI"],
    ["NORDFELDT Kristoffer", "NORDFELDT"],
    ["STROUD Elliot", "STROUD"],
    ["NILSSON Gustaf", "NILSSON"],
    ["ALI Taha", "ALI"],
  ],
  "sn": [
    ["DIOUF Yehvann", "Y. DIOUF"],
    ["SARR Mamadou", "SARR"],
    ["KOULIBALY Kalidou", "KOULIBALY"],
    ["SECK Abdoulaye", "SECK"],
    ["GUEYE Idrissa Gana", "GANA"],
    ["CISS Pathe", "P.I. CISS"],
    ["DIAO Assane", "A. DIAO"],
    ["CAMARA Lamine", "LAMINE"],
    ["DIENG Bamba", "BAMBA"],
    ["MANE Sadio", "MANÉ"],
    ["JACKSON Nicolas", "N. JACKSON"],
    ["NDIAYE Cherif", "CHÉRIF"],
    ["NDIAYE Iliman", "NDIAYE"],
    ["JAKOBS Ismail", "JAKOBS"],
    ["DIATTA Krepin", "DIATTA"],
    ["MENDY Edouard", "MENDY"],
    ["SARR Pape Matar", "P.M. SARR"],
    ["SARR Ismaila", "ISMAÏLA"],
    ["NIAKHATE Moussa", "NIAKHATÉ"],
    ["MBAYE Ibrahim", "I. MBAYE"],
    ["DIARRA Habib", "H. DIARRA"],
    ["NDIAYE Bara Sapoko", "BARA"],
    ["DIAW Mory", "DIAW"],
    ["MENDY Antoine", "A. MENDY"],
    ["DIOUF El Hadji Malick", "DIOUF"],
    ["GUEYE Pape", "GUEYE"],
  ],
  "tn": [
    ["CHAMAKH Mouhib", "CHAMAKH"],
    ["ABDI Ali", "ABDI"],
    ["TALBI Montassar", "TALBI"],
    ["REKIK Omar", "REKIK"],
    ["AROUS Adam", "AROUS"],
    ["BRONN Dylan", "BRONN"],
    ["ACHOURI Elias", "ACHOURI"],
    ["SAAD Elias", "SAAD"],
    ["MASTOURI Hazem", "MASTOURI"],
    ["MEJBRI Hannibal", "HANNIBAL"],
    ["GHARBI Ismael", "GHARBI"],
    ["BEN OUANES Mortadha", "BEN OUANES"],
    ["KHEDIRA Rani", "KHEDIRA"],
    ["AYARI Khalil", "AYARI"],
    ["HADJ MAHMOUD Mohamed", "HADJ MAHMOUD"],
    ["DAHMEN Aymen", "DAHMEN"],
    ["SKHIRI Ellyes", "SKHIRI"],
    ["ELLOUMI Rayan", "ELLOUMI"],
    ["CHAOUAT Firas", "CHAOUAT"],
    ["VALERY Yan", "VALERY"],
    ["BEN HMIDA Mohamed Amine", "BEN HMIDA"],
    ["BEN HESSEN Sabri", "BEN HESSEN"],
    ["NEFFATI Moutaz", "NEFFATI"],
    ["CHIKHAOUI Raed", "CHIKHAOUI"],
    ["SLIMANE Anis", "SLIMANE"],
    ["TOUNEKTI Sebastian", "TOUNEKTI"],
  ],
  "tr": [
    ["GUNOK Mert", "MERT"],
    ["CELIK Zeki", "ZEKİ ÇELİK"],
    ["DEMIRAL Merih", "DEMİRAL"],
    ["SOYUNCU Caglar", "ÇAĞLAR"],
    ["OZCAN Salih", "ÖZCAN"],
    ["KOKCU Orkun", "ORKUN KÖKÇÜ"],
    ["AKTURKOGLU Kerem", "AKTÜRKOĞLU"],
    ["GULER Arda", "ARDA GÜLER"],
    ["GUL Deniz", "DENİZ GÜL"],
    ["CALHANOGLU Hakan", "ÇALHANOĞLU"],
    ["YILDIZ Kenan", "YILDIZ"],
    ["BAYINDIR Altay", "ALTAY"],
    ["ELMALI Eren", "EREN ELMALI"],
    ["BARDAKCI Abdulkerim", "ABDÜLKERİM"],
    ["KABAK Ozan", "OZAN KABAK"],
    ["YUKSEK Ismail", "İSMAİL"],
    ["KAHVECI Irfan Can", "KAHVECİ"],
    ["MULDUR Mert", "MERT MÜLDÜR"],
    ["AKGUN Yunus", "YUNUS"],
    ["KADIOGLU Ferdi", "F. KADIOĞLU"],
    ["YILMAZ Baris Alper", "BARIŞ"],
    ["AYHAN Kaan", "KAAN"],
    ["CAKIR Ugurcan", "UĞURCAN"],
    ["AYDIN Oguz", "OĞUZ"],
    ["AKAYDIN Samet", "SAMET AKAYDIN"],
    ["UZUN Can", "CAN UZUN"],
  ],
  "us": [
    ["TURNER Matt", "TURNER"],
    ["DEST Sergino", "DEST"],
    ["RICHARDS Chris", "RICHARDS"],
    ["ADAMS Tyler", "ADAMS"],
    ["ROBINSON Antonee", "A. ROBINSON"],
    ["TRUSTY Auston", "TRUSTY"],
    ["REYNA Giovanni", "REYNA"],
    ["McKENNIE Weston", "MCKENNIE"],
    ["PEPI Ricardo", "PEPI"],
    ["PULISIC Christian", "PULISIC"],
    ["AARONSON Brenden", "AARONSON"],
    ["ROBINSON Miles", "M. ROBINSON"],
    ["REAM Tim", "REAM"],
    ["BERHALTER Sebastian", "BERHALTER"],
    ["ROLDAN Cristian", "ROLDAN"],
    ["FREEMAN Alex", "FREEMAN"],
    ["TILLMAN Malik", "TILLMAN"],
    ["ARFSTEN Max", "ARFSTEN"],
    ["WRIGHT Haji", "WRIGHT"],
    ["BALOGUN Folarin", "BALOGUN"],
    ["WEAH Timothy", "WEAH"],
    ["McKENZIE Mark", "MCKENZIE"],
    ["SCALLY Joe", "SCALLY"],
    ["FREESE Matt", "FREESE"],
    ["BRADY Chris", "BRADY"],
    ["ZENDEJAS Alex", "ZENDEJAS"],
  ],
  "uy": [
    ["ROCHET Sergio", "S. ROCHET"],
    ["GIMENEZ Jose Maria", "J.M. GIMÉNEZ"],
    ["CACERES Sebastian", "S. CACERES"],
    ["ARAUJO Ronald", "R. ARAUJO"],
    ["UGARTE Manuel", "M. UGARTE"],
    ["BENTANCUR Rodrigo", "R. BENTANCUR"],
    ["DE LA CRUZ Nicolas", "N. DE LA CRUZ"],
    ["VALVERDE Federico", "F. VALVERDE"],
    ["NUNEZ Darwin", "D. NUÑEZ"],
    ["DE ARRASCAETA Giorgian", "G. DE ARRASCAETA"],
    ["PELLISTRI Facundo", "F. PELLISTRI"],
    ["MELE Santiago", "S. MELE"],
    ["VARELA Guillermo", "G. VARELA"],
    ["CANOBBIO Agustin", "A. CANOBBIO"],
    ["MARTINEZ Emiliano", "E. MARTINEZ"],
    ["OLIVERA Mathias", "M. OLIVERA"],
    ["VINA Matias", "M. VIÑA"],
    ["RODRIGUEZ Brian", "B. RODRIGUEZ"],
    ["AGUIRRE Rodrigo", "R. AGUIRRE"],
    ["ARAUJO Maxi", "M. ARAUJO"],
    ["VINAS Federico", "F. VIÑAS"],
    ["PIQUEREZ Joaquin", "J. PIQUEREZ"],
    ["MUSLERA Fernando", "F. MUSLERA"],
    ["BUENO Santiago", "S. BUENO"],
    ["SANABRIA Juan Manuel", "J.M. SANABRIA"],
    ["ZALAZAR Rodrigo", "R. ZALAZAR"],
  ],
  "uz": [
    ["YUSUPOV Utkir", "YUSUPOV"],
    ["KHUSANOV Abdukodir", "KHUSANOV"],
    ["ALIJONOV Khojiakbar", "ALIJONOV"],
    ["SAYFIEV Farrukh", "SAYFIEV"],
    ["ASHURMATOV Rustam", "ASHURMATOV"],
    ["MOZGOVOY Akmal", "MOZGOVOY"],
    ["SHUKUROV Otabek", "SHUKUROV"],
    ["ISKANDEROV Jamshid", "ISKANDEROV"],
    ["XAMROBEKOV Odiljon", "XAMROBEKOV"],
    ["JIYANOV Ruslanbek", "JIYANOV"],
    ["URUNOV Oston", "URUNOV"],
    ["NEMATOV Abduvohid", "NEMATOV"],
    ["NASRULLAEV Sherzod", "NASRULLAEV"],
    ["SHOMURODOV Eldor", "SHOMURODOV"],
    ["ESHMURODOV Umar", "ESHMURODOV"],
    ["ERGASHEV Botirali", "ERGASHEV"],
    ["KHAMDAMOV Dostonbek", "KHAMDAMOV"],
    ["ABDULLAEV Abdulla", "ABDULLAEV"],
    ["GANIEV Azizjon", "GANIEV"],
    ["AMONOV Azizbek", "AMONOV"],
    ["SERGEEV Igor", "SERGEEV"],
    ["FAYZULLAEV Abbosbek", "FAYZULLAEV"],
    ["ESANOV Sherzod", "ESANOV"],
    ["KARIMOV Behruzjon", "KARIMOV"],
    ["ULMASALIYEV Avazbek", "ULMASALIYEV"],
    ["UROZOV Jakhongir", "UROZOV"],
  ],
  "za": [
    ["WILLIAMS Ronwen", "WILLIAMS"],
    ["MATULUDI Thabang", "MATULUDI"],
    ["NDAMANE Khulumani", "NDAMANE"],
    ["MOKOENA Teboho", "MOKOENA"],
    ["MBATHA Thalente", "MBATHA"],
    ["MODIBA Aubrey", "MODIBA"],
    ["APPOLLIS Oswin", "APPOLLIS"],
    ["MOREMI Tshepang", "MOREMI"],
    ["FOSTER Lyle", "FOSTER"],
    ["MOFOKENG Relebohile", "MOFOKENG"],
    ["ZWANE Themba", "ZWANE"],
    ["MASEKO Thapelo", "MASEKO"],
    ["SITHOLE Sphephelo", "SITHOLE"],
    ["MBOKAZI Mbekezeli", "MBOKAZI"],
    ["RAYNERS Iqraam", "RAYNERS"],
    ["CHAINE Sipho", "CHAINE"],
    ["MAKGOPA Evidence", "MAKGPA"],
    ["KABINI Samukele", "KABINI"],
    ["SIBISI Nkosinathi", "SIBISI"],
    ["MUDAU Khuliso", "MUDAU"],
    ["OKON Ime", "OKON"],
    ["GOSS Ricardo", "GOSS"],
    ["ADAMS Jayden", "ADAMS"],
    ["MAKHANYA Olwethu", "MAKHANYA"],
    ["SEBELEBELE Kamogelo", "SEBELEBELE"],
    ["CROSS Bradley", "CROSS"],
  ],
};
